version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
    # command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle 
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  mysql-data:
    driver: local
  bundle:
  public-data:
  tmp-data: